### ISSUE TITLE
bundler: command not found: jekyll

### ISSUE THREAD

**Issue by hrushikeshrv** [just-the-docs/just-the-docs-template#26]
I'm trying to add the just-the-docs theme to an existing repo, and I've done the following -

1. Copied Gemfile from this template repo to mine in the root directory
3. Copied Gemfile.lock from this template repo to mine in the root directory
4. Created the .github/workflows directory and copied the pages.yml file into it
5. Modified the pages.yml file as instructed in the README
6. Configured GitHub pages by going to my repo's Settings > Pages tab and setting the source as GitHub Actions instead of "Deploy from a branch"
7. Created a _config.yml file in the root directory with the following content (according to the GitHub docs)

```
remote-theme: just-the-docs
```

But whenever I push changes to the docs or re-run the action, It fails with the message `bundler: command not found: jekyll`.

<img width="1007" alt="image" src="https://github.com/just-the-docs/just-the-docs-template/assets/64729027/08b976b7-8a6d-4f40-89df-0c2bddb9efbe">

This is my first time working with Jekyll, and I can't figure out if I'm doing something wrong. Any help would be appreciated!

**Comment by mattxwang** [comment]
Thanks for submitting an issue @hrushikeshrv! Did you also copy over the Ruby setup portion of `pages.yml`? From your screenshot, it's not clear if that's run (that portion of the YAML file, among other things, runs `bundle install`).

In particular, I'm referencing this part of the workflow:

```yaml
   - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
```

(if you haven't, I would encourage just copying over the entire file itself, instead of doing it piecewise)
